export const SET_HOME_SCREEN_REFRESHING = 'SET_HOME_SCREEN_REFRESHING';
export const ADD_ARTICLE = 'ADD_ARTICLE';
export const SET_ARTICLES = 'SET_ARTICLES';
export const SET_SUBSCRIPTIONS = 'SET_SUBSCRIPTIONS';
export const ADD_SUBSCRIPTION_ARTICLES = 'ADD_SUBSCRIPTION_ARTICLES';
export const TOGGLE_ACTIVE_SUB_FILTER = 'TOGGLE_ACTIVE_SUB_FILTER';
export const SET_ARCHIVE_ISSUES = 'SET_ARCHIVE_ISSUES';
