export const ADD_ARTICLE = 'ADD_ARTICLE';
export const SET_ARTICLES = 'SET_ARTICLES';
export const SET_SUBSCRIPTIONS = 'SET_SUBSCRIPTIONS';
export const ADD_SUBSCRIPTION_ARTICLES = 'ADD_SUBSCRIPTION_ARTICLES';
export const TOGGLE_ACTIVE_SUB_FILTER = 'TOGGLE_ACTIVE_SUB_FILTER';
