export const ADD_ARTICLE = 'ADD_ARTICLE';
export const SET_ARTICLES = 'SET_ARTICLES';
export const GET_TOKEN = 'GET_TOKEN';
export const SET_TOKENS = 'SET_TOKENS';
export const SET_SUBSCRIPTIONS = 'SET_SUBSCRIPTIONS';
export const SET_ACTIVE_SUB_FILTER = 'SET_ACTIVE_SUB_FILTER';
